apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.appName | lower }}-servicesettings
  namespace: {{ .Values.namespace | lower }}
  labels:
    app.kubernetes.io/name: {{ include "app-chart.name" . }}
    helm.sh/chart: {{ include "app-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}  
data:
  serviceSettings.json: |-
      {
        "ConsulSettings": {
          "Host": "http://consul-server.consul:8500",
          "Path": "{{ .Values.environment }}/bim_resource_api/appsettings.json",
          "AccessToken": "9808f960-6697-6a72-d5d3-cd36fd62ef7b",
          "FailDelay": 10000,
          "PollDelay": 10000,
          "SpamDelay": 10000
        }
      }
      