apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.appName | lower }}
  namespace: {{ .Values.namespace | lower }}
  labels:
    app.kubernetes.io/name: {{ include "app-chart.name" . }}
    helm.sh/chart: {{ include "app-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ $.Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pod.port }}
              protocol: TCP
          volumeMounts:
          - name: {{ $.Values.appName | lower }}-servicesettings
            mountPath: /app/config/serviceSettings.json
            subPath: serviceSettings.json               
          #env:
          #- name: DB_CONNECTION
          #  value: "{{ .Values.appconfig.dbConnection }}"
          #- name: ASPNETCORE_ENVIRONMENT
          #  value: "{{ .Values.environment }}"            
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http            
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: {{ $.Values.appName | lower }}-servicesettings
        configMap:
          name: {{ $.Values.appName | lower }}-servicesettings     

      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

